### ISSUE TITLE
Getting: "gpxpy.gpx.GPXException: latitude is mandatory in None (got None)"

### ISSUE THREAD

**Issue by dhruv-jadhav** [marcusvolz/strava_py#23]
Hey, 

I tried using the CLI tool but I'm getting this error: ```gpxpy.gpx.GPXException: latitude is mandatory in None (got None)```

I tried setting `--lon_max, --lat_max` to ```180,90``` and `--lat_min, --lon_min` to ```0,0``` but still getting the same error.

Is this a problem with a specific .gpx file? And if so how can I find that one because the error doesn't show which file. 

Thanks

**Comment by hugovk** [comment]
Yes, I've seen this and it's a problem with a specific .gpx file.

I think we should fix this to print the name of the problematic file, skip it and continue.

In the meantime, you can temporarily add this to `stravavis/process_data.py` (its location should be printed in your full traceback):
 

```diff
 def process_gpx(gpxfile):
+    print(gpxfile)
     with open(gpxfile, encoding="utf-8") as f:
         activity = gpxpy.parse(f) 
```

The either delete the gpx file, or in my case I opened it in a text editor, and found and deleted the problematic `<trkpt>` (it was the first one):

```xml
      <trkpt>
        <ele>31.2</ele>
        <time>2019-08-31T09:02:36Z</time>
        <extensions>
          <gpxdata:temp>0</gpxdata:temp>
        </extensions>
      </trkpt>
```

The rest all have `lon` and `lat` values, like this:

```xml
      <trkpt lon="24.12345" lat="60.12345">
        <ele>31.2</ele>
        <time>2019-08-31T09:02:37Z</time>
        <extensions>
          <gpxdata:temp>29</gpxdata:temp>
        </extensions>
```

**Comment by hugovk** [comment]
Please see PR https://github.com/marcusvolz/strava_py/pull/27 to fix this.

**Comment by dhruv-jadhav** [comment]
Great, the fix works perfectly!

**Comment by hugovk** [comment]
Good to hear! I'll merge that and put out a new release so people can do their year-end visualisations!

I'm curious, do you know what the problem with your GPX file is? Is it the same thing as I had above?

Mine was one that had been combined using the [GOTOES utilities](https://gotoes.org/strava/Combine_GPX_TCX_FIT_Files.php).

**Comment by dhruv-jadhav** [comment]
Yep, I had problems with the files which were merged using GOTOES.
![image](https://user-images.githubusercontent.com/66950413/210093213-b6d3e632-d8ac-4168-88e0-a2892d346916.png)

**Comment by marcusvolz** [comment]
Many thanks @hugovk for this and all the recent updates!

**Comment by dhruv-jadhav** [comment]
Yes, thanks a lot @hugovk! Strava's Year In Sport was behind a paywall this year so this package helped me get a certain level of satisfaction. Great work!
